"""empty message

Revision ID: 2d09d161426f
Revises: 87a25a3360d7
Create Date: 2024-05-13 14:23:14.350440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d09d161426f'
down_revision = '87a25a3360d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrate_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrate_table', schema=None) as batch_op:
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
