"""empty message

Revision ID: 48ebb12d9496
Revises: 03631012718e
Create Date: 2024-05-13 11:52:52.964337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48ebb12d9496'
down_revision = '03631012718e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bakery_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bakery_id'], ['bakery.id'], name=op.f('fk_table_bakery_id_bakery')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_table'))
    )
    op.create_table('registrate_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('surname', sa.String(length=32), nullable=False),
    sa.Column('patronymics', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('bakery_id', sa.Integer(), nullable=True),
    sa.Column('data_registrate', sa.DateTime(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bakery_id'], ['bakery.id'], name=op.f('fk_registrate_table_bakery_id_bakery')),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('fk_registrate_table_order_id_order')),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], name=op.f('fk_registrate_table_table_id_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registrate_table')),
    sa.UniqueConstraint('trace_id', name=op.f('uq_registrate_table_trace_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registrate_table')
    op.drop_table('table')
    # ### end Alembic commands ###
