"""empty message

Revision ID: 69db6a9d638e
Revises: 2da563dd89a6
Create Date: 2023-11-23 19:36:50.408746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69db6a9d638e'
down_revision = '2da563dd89a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sweet_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=32), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sweet_product', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
