"""empty message

Revision ID: 7e732552f154
Revises: 69db6a9d638e
Create Date: 2023-11-26 15:11:22.441372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e732552f154'
down_revision = '69db6a9d638e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_to_sweet_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_to_sweet_product', schema=None) as batch_op:
        batch_op.drop_column('count')

    # ### end Alembic commands ###
