"""empty message

Revision ID: 87a25a3360d7
Revises: 48ebb12d9496
Create Date: 2024-05-13 12:32:58.626059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a25a3360d7'
down_revision = '48ebb12d9496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrate_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_registrate', sa.Enum('waiting_for_payment', 'paid', 'waiting_for_confirmation', 'confirmed', 'prepared', 'ready', 'waiting_for_the_courier', 'delivery', 'completed', name='statusorder'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrate_table', schema=None) as batch_op:
        batch_op.drop_column('status_registrate')

    # ### end Alembic commands ###
