"""empty message

Revision ID: c3c2a0ddfab0
Revises: 7bcec93ff803
Create Date: 2023-11-29 14:07:55.684676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3c2a0ddfab0'
down_revision = '7bcec93ff803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakery', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_bakery_trace_id'), ['trace_id'])

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_order_trace_id'), ['trace_id'])

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_role_name'), ['name'])

    with op.batch_alter_table('sweet_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_sweet_product_trace_id'), ['trace_id'])
        batch_op.create_foreign_key(batch_op.f('fk_sweet_product_type_id_type'), 'type', ['type_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_trace_id'), ['trace_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_trace_id'), type_='unique')

    with op.batch_alter_table('sweet_product', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sweet_product_type_id_type'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_sweet_product_trace_id'), type_='unique')
        batch_op.drop_column('type_id')

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_role_name'), type_='unique')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_order_trace_id'), type_='unique')

    with op.batch_alter_table('bakery', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_bakery_trace_id'), type_='unique')

    # ### end Alembic commands ###
