from .UserRepository import UserRepository
from .SweetProductRepository import SweetProductRepository
from .BakeryRepository import BakeryRepository
from .OrderRepository import OrderRepository
from .RegistrateTableRepository import RegistrateTableRepository
