from .LogInForm import LoginForm
from .RegistrationForm import RegistrationForm
from .CreateOrderForm import CreateOrderForm
from .UserForm import UserForm
from .OrderUpdateForm import OrderUpdateForm
from .OrderSweetUpdateForm import OrderSweetUpdateForm
from .SearchOrderWorkerForm import SearchOrderWorkerForm
from .SearchSweetProduct import SearchSweetProduct
from .RegTableForm import RegTableFrom
from .SearchRegTableForm import SearchRegTableForm
from .RegTableUpdateForm import RegTableUpdateFrom
from .OrderSweetUpdateForm import OrderSweetUpdateForm